version: '3'

services:
  app:
    container_name: "translator-container"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - YANDEX_API_KEY=
      - YANDEX_FOLDER_ID=
      - DB_NAME=
      - DB_USER=
      - DB_PASSWORD=